import { useEffect, useState } from 'react'
import PageHeader from '../components/PageHeader'
import Button from '../components/Button'
import Loader from '../components/Loader'
import Icon from '../components/Icon'
import { assetRecords } from '../data/records'
const stats=[['Total students','1,248','+8.2%','students','violet'],['Available assets','342','+12.5%','assets','blue'],['In use','286','+4.1%','check','mint'],['Needs attention','18','Review now','alert','amber']]
export default function Dashboard({notify}) { const [loading,setLoading]=useState(true); useEffect(()=>{const id=setTimeout(()=>setLoading(false),350);return()=>clearTimeout(id)},[]); if(loading)return <Loader/>; return <><PageHeader title="Good morning, Alex" description="Here’s what’s happening with your inventory today." action={<Button icon="plus" onClick={()=>notify({title:'Quick action ready',text:'Use the Assets menu to create a record.'})}>Add new asset</Button>}/><section className="stat-grid">{stats.map(([label,value,trend,icon,tone])=><article className="stat-card" key={label}><div className={`stat-icon ${tone}`}><Icon name={icon} size={21}/></div><div><p>{label}</p><h2>{value}</h2><small className={tone==='amber'?'attention':''}>{tone==='amber'?'':'↗ '}{trend}</small></div></article>)}</section><section className="dashboard-grid"><article className="panel activity-panel" id="activity"><div className="panel-heading"><div><h3>Inventory activity</h3><p>Asset movements over the last 7 days</p></div><button className="quiet-button">This week <Icon name="down" size={13}/></button></div><div className="chart"><div className="chart-y"><span>80</span><span>60</span><span>40</span><span>20</span><span>0</span></div><div className="chart-bars">{[32,48,38,70,54,66,43].map((h,i)=><div className="bar-slot" key={i}><i style={{height:`${h}%`}}/><span>{['Mon','Tue','Wed','Thu','Fri','Sat','Sun'][i]}</span></div>)}</div></div></article><article className="panel allocation-panel"><div className="panel-heading"><div><h3>Asset allocation</h3><p>Current distribution by status</p></div><Icon name="more"/></div><div className="donut"><div><b>646</b><span>Assets</span></div></div><div className="legend"><p><i className="purple"/>In use <b>286</b></p><p><i className="blue"/>Available <b>342</b></p><p><i className="amber"/>Maintenance <b>18</b></p></div></article></section><section className="panel recent-panel"><div className="panel-heading"><div><h3>Recently updated</h3><p>Your latest asset changes</p></div><button className="text-button">View all <Icon name="arrow" size={15}/></button></div><AssetTable records={assetRecords}/></section></> }
export function AssetTable({ records }) { return <div className="table-wrap"><table><thead><tr><th>RECORD</th><th>ASSIGNED TO</th><th>STATUS</th><th>UPDATED</th><th/></tr></thead><tbody>{records.map(record=><tr key={record.id}><td><span className="asset-avatar">{record.name[0]}</span><div><b>{record.name}</b><small>{record.id}</small></div></td><td>{record.owner}</td><td><span className={`status ${record.color}`}>{record.status}</span></td><td>{record.updated}</td><td><button className="more"><Icon name="more" size={18}/></button></td></tr>)}</tbody></table></div> }
